### ISSUE TITLE
Tiles in Output Postscript graphs 

### ISSUE THREAD

**Issue by mberry28** [danigeos/tisc#1]
Is it possible to turn on and off which visual outputs are plotted in via GMT? For example, if I wanted to only see the map view of topography and drainage (not sediment thickness, erosion rate, etc) and a cross section of a selected region, is there a way to "switch off" the unwanted plots?

**Comment by danigeos** [comment]
TISC calls the script tisc.gmt.job when finishing. This script uses GMT commands to produce the graphics. It looks for that file in your path, so you can make a copy of the original example in your project directory (where you run tisc) and then edit the file and change whatever you want. You can also make a symbolic link to any of the example scripts in tisc/script, like this:
ln -s ./tisc/script/tisc.sedims+deflect.gmt.job tisc.gmt.job

Or better just copy the file to your directory, since eventually you will want to edit it to do exactly what you want.
